apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command: ['sh', '-c', 'until nc -z auth-mongo-srv 27017; do echo waiting for mongo; sleep 2; done']
      containers:
        - name: auth
          image: kingsley555/auth
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: hotels-secrets
                  key: MONGO_URI
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: hotels-secrets
                  key: JWT_KEY
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                configMapKeyRef:
                  name: hotels-configmap
                  key: NEW_RELIC_LICENSE_KEY
            - name: NEW_RELIC_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: hotels-configmap
                  key: NEW_RELIC_APP_NAME       
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
