apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq-srv 5672; do echo waiting for rabbitmq; sleep 2; done']
        - name: wait-for-redis
          image: busybox
          command: ['sh', '-c', 'until nc -z expiration-redis-srv 6379; do echo waiting for redis; sleep 2; done']
      containers:
        - name: expiration
          image: kingsley555/expiration
          env:
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: hotels-secrets
                  key: RABBITMQ_URL
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: hotels-secrets
                  key: REDIS_HOST
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                configMapKeyRef:
                  name: hotels-configmap
                  key: NEW_RELIC_LICENSE_KEY
            - name: NEW_RELIC_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: hotels-configmap
                  key: NEW_RELIC_APP_NAME       
