apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotels
  template:
    metadata:
      labels:
        app: hotels
    spec:
      containers:
        - name: hotels
          image: kingsley555/hotels
          env:
            - name: RABBITMQ_URL
              value: 'amqp://rabbitmq-srv:5672'
            - name: MONGO_URI_HOTEL
              valueFrom:
                secretKeyRef:
                  name: mongo-uri-hotel
                  key: MONGO_URI_HOTEL
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: hotels-srv
spec:
  selector:
    app: hotels
  ports:
    - name: hotels
      protocol: TCP
      port: 3000
      targetPort: 3000
