apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotels
  template:
    metadata:
      labels:
        app: hotels
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command: ['sh', '-c', 'until nc -z hotels-mongo-srv 27017; do echo waiting for mongo; sleep 2; done']
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq-srv 5672; do echo waiting for rabbitmq; sleep 2; done']
      containers:
        - name: hotels
          image: kingsley555/hotels
          env:
            - name: MONGO_URI_HOTEL
              valueFrom:
                secretKeyRef:
                  name: hotels-secrets
                  key: MONGO_URI_HOTEL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: hotels-secrets
                  key: RABBITMQ_URL
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: hotels-secrets
                  key: JWT_KEY
            - name: CLOUDINARY_NAME
              valueFrom:
                configMapKeyRef:
                  name: hotels-configmap
                  key: CLOUDINARY_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: hotels-configmap
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                configMapKeyRef:
                  name: hotels-configmap
                  key: CLOUDINARY_API_SECRET
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                configMapKeyRef:
                  name: hotels-configmap
                  key: NEW_RELIC_LICENSE_KEY
            - name: NEW_RELIC_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: hotels-configmap
                  key: NEW_RELIC_APP_NAME          
---
apiVersion: v1
kind: Service
metadata:
  name: hotels-srv
spec:
  selector:
    app: hotels
  ports:
    - name: hotels
      protocol: TCP
      port: 3000
      targetPort: 3000
