apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command: ['sh', '-c', 'until nc -z payments-mongo-srv 27017; do echo waiting for mongo; sleep 2; done']
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq-srv 5672; do echo waiting for rabbitmq; sleep 2; done']
      containers:
        - name: payments
          image: kingsley555/payments
          env:
            - name: MONGO_URI_PAYMENTS
              valueFrom:
                secretKeyRef:
                  name: hotels-secrets
                  key: MONGO_URI_PAYMENTS
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: hotels-secrets
                  key: RABBITMQ_URL
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: hotels-secrets
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                configMapKeyRef:
                  name: hotels-configmap
                  key: STRIPE_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
